<?xml version="1.0" encoding="utf-8"?><Database Name="CRUDELEVATEC" Class="SPElevatecDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QETR9PD;Initial Catalog=CRUDELEVATEC;Integrated Security=True" SettingsObjectName="crud.Properties.Settings" SettingsPropertyName="CRUDELEVATECConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_computerInsert" Method="sp_computerInsert">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="computadora" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="entrada" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="salida" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="proyecto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tecnico" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_computerList" Method="sp_computerList">
    <ElementType Name="sp_computerListResult">
      <Column Name="idInfo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Computadora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="proyecto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tecnico" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_computerUPDATE" Method="sp_computerUPDATE">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="computadora" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="entrada" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="salida" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="proyecto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tecnico" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_computerDELETE" Method="sp_computerDELETE">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_computerSearch" Method="sp_computerSearch">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_computerSearchResult">
      <Column Name="idInfo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Computadora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="proyecto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tecnico" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>