#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRUDELEVATEC")]
	public partial class SPElevatecDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SPElevatecDataContext() : 
				base(global::crud.Properties.Settings.Default.CRUDELEVATECConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SPElevatecDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPElevatecDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPElevatecDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPElevatecDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_computerInsert")]
		public int sp_computerInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string computadora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> entrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> salida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string proyecto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tecnico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string observacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, computadora, entrada, salida, proyecto, tecnico, observacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_computerList")]
		public ISingleResult<sp_computerListResult> sp_computerList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_computerListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_computerUPDATE")]
		public int sp_computerUPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string computadora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> entrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> salida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string proyecto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tecnico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string observacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, computadora, entrada, salida, proyecto, tecnico, observacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_computerDELETE")]
		public int sp_computerDELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_computerSearch")]
		public ISingleResult<sp_computerSearchResult> sp_computerSearch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_computerSearchResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_computerListResult
	{
		
		private int _idInfo;
		
		private string _Computadora;
		
		private System.Nullable<System.DateTime> _salida;
		
		private System.Nullable<System.DateTime> _entrada;
		
		private string _proyecto;
		
		private string _tecnico;
		
		private string _observacion;
		
		public sp_computerListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInfo", DbType="Int NOT NULL")]
		public int idInfo
		{
			get
			{
				return this._idInfo;
			}
			set
			{
				if ((this._idInfo != value))
				{
					this._idInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Computadora", DbType="VarChar(50)")]
		public string Computadora
		{
			get
			{
				return this._Computadora;
			}
			set
			{
				if ((this._Computadora != value))
				{
					this._Computadora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salida", DbType="DateTime")]
		public System.Nullable<System.DateTime> salida
		{
			get
			{
				return this._salida;
			}
			set
			{
				if ((this._salida != value))
				{
					this._salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> entrada
		{
			get
			{
				return this._entrada;
			}
			set
			{
				if ((this._entrada != value))
				{
					this._entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proyecto", DbType="VarChar(50)")]
		public string proyecto
		{
			get
			{
				return this._proyecto;
			}
			set
			{
				if ((this._proyecto != value))
				{
					this._proyecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tecnico", DbType="VarChar(50)")]
		public string tecnico
		{
			get
			{
				return this._tecnico;
			}
			set
			{
				if ((this._tecnico != value))
				{
					this._tecnico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="VarChar(200)")]
		public string observacion
		{
			get
			{
				return this._observacion;
			}
			set
			{
				if ((this._observacion != value))
				{
					this._observacion = value;
				}
			}
		}
	}
	
	public partial class sp_computerSearchResult
	{
		
		private int _idInfo;
		
		private string _Computadora;
		
		private System.Nullable<System.DateTime> _salida;
		
		private System.Nullable<System.DateTime> _entrada;
		
		private string _proyecto;
		
		private string _tecnico;
		
		private string _observacion;
		
		public sp_computerSearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInfo", DbType="Int NOT NULL")]
		public int idInfo
		{
			get
			{
				return this._idInfo;
			}
			set
			{
				if ((this._idInfo != value))
				{
					this._idInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Computadora", DbType="VarChar(50)")]
		public string Computadora
		{
			get
			{
				return this._Computadora;
			}
			set
			{
				if ((this._Computadora != value))
				{
					this._Computadora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salida", DbType="DateTime")]
		public System.Nullable<System.DateTime> salida
		{
			get
			{
				return this._salida;
			}
			set
			{
				if ((this._salida != value))
				{
					this._salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> entrada
		{
			get
			{
				return this._entrada;
			}
			set
			{
				if ((this._entrada != value))
				{
					this._entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proyecto", DbType="VarChar(50)")]
		public string proyecto
		{
			get
			{
				return this._proyecto;
			}
			set
			{
				if ((this._proyecto != value))
				{
					this._proyecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tecnico", DbType="VarChar(50)")]
		public string tecnico
		{
			get
			{
				return this._tecnico;
			}
			set
			{
				if ((this._tecnico != value))
				{
					this._tecnico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="VarChar(200)")]
		public string observacion
		{
			get
			{
				return this._observacion;
			}
			set
			{
				if ((this._observacion != value))
				{
					this._observacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
